USE movie_dataset;

DROP TABLE temporalCast;
CREATE TABLE temporalCast(
    columnReplaced VARCHAR(255)
);


INSERT INTO temporalCast(columnReplaced)
SELECT
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
            REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                            REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                            REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                            REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                                    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                                        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                                            REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                                                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( REPLACE(REPLACE(
                                                                                    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                                                                        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( REPLACE(REPLACE(REPLACE(
                                                                                            REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( REPLACE(REPLACE(REPLACE(
                                                                                                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( REPLACE(REPLACE(REPLACE(
                                                                                                     REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( REPLACE(REPLACE(REPLACE(
                                                                                                          REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( REPLACE(REPLACE(REPLACE(
                                                                                                               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE( REPLACE(REPLACE(REPLACE(
                                                                                                                    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
    cast,
    '\\u00e1' , 'á'),
    '\\u00c1' , 'Á'),
    '\\u00c5' , 'Å'),
    '\\u00c0' , 'À'),
    '\\u00e5' , 'å'),
    '\\u00e4' , 'ä'),
    '\\u00e0' , 'à'),
    '\\u0101' , 'ā'),
    '\\u1ea3' , 'à'),
    '\\u00e6' , 'æ'),
    '\\u00df' , 'ß'),
    '\\u00e7' , 'ç'),
    '\\u010d' , 'č'),
    '\\u0107' , 'ć'),
    '\\u011f' , 'ğ'),
    '\\u00e9' , 'é'),
    '\\u1ec1' , 'ề'),
    '\\u00e8' , 'è'),
    '\\u00ea' , 'ê'),
    '\\u00eb' , 'ë'),
    '\\u1ebf' , 'ế'),
    '\\u00c9' , 'É'),
    '\\u00fa' , 'ú'),
    '\\u00fc' , 'ü'),
    '\\u016b' , 'ū'),
    '\\u00fb' , 'û'),
    '\\u00dc' , 'Ü'),
    '\\u00ed' , 'í'),
    '\\u00ef' , 'ï'),
    '\\u00ee' , 'î'),
    '\\u0131' , 'ı'),
    '\\u1ecb' , 'ị'),
    '\\u015e' , 'Ş'),
    '\\u0219' , 'ș'),
    '\\u015f' , 'ş'),
    '\\u0161' , 'š'),
    '\\u015b' , 'ś'),
    '\\u0160' , 'Š'),
    '\\u0144' , 'ń'),
    '\\u00f1' , 'ñ'),
    '\\u0110' , 'Đ'),
    '\\u00d8' , 'Ø'),
    '\\u00f8' , 'ø'),
    '\\u00f6' , 'ö'),
    '\\u00d3' , 'Ó'),
    '\\u00f3' , 'ó'),
    '\\u014d' , 'ō'),
    '\\u00f4' , 'ô'),
    '\\u00f6' , 'ö'),
    '\\u1ed7' , 'ỗ'),
    '\\u00f0' , 'ð'),
    '\\u0159' , 'ř'),
    '\\u2019' , '’'),
    '\\u021b' , 'ț'),
    '\\u017e' , 'ž'),
    '\\u042e\\u043b\\u0438\\u044f \\u0421\\u043d\\u0438\\u0433\\u0438\\u0440\\u044c', 'Yuliya Snigir'),
    '\\u067e\\u06cc\\u0645\\u0627\\u0646 \\u0645\\u0639\\u0627\\u062f\\u06cc' , 'Payman Maadi'),

    ' Jr.' , '_Jr.'),
    ', _Jr' , '_Jr.'),
    'A. ' , 'A._'),
    'F. ' , 'F._'),
    'A.J. ' , 'A._J. '),
    'St. ' , 'St._'),
    ' L. ' , ' L._'),
    'S. ' , 'S._'),
    ' B. ' , '_B. '),
    ' E. ' , '_E. '),
    ' D. ' , ' D._'),
    ' C. ' , '_C. '),
    'R. ' , 'R._'),
    ' J. ' , ' J._'),
    ' T. ' , ' T._'),
    'T.I.' , 'T.I. ^'),
    ' H. ' , ' H._'),
    ' G. ' , ' G._'),
    ' P. ' , ' P._'),
    'M. ' , 'M._'),
    ' de la ' , ' de_la_'),
    ' de ' , ' de_'),
    ' La ' , ' La_'),
    ' Le ' , ' Le_'),
    ' De ' , ' De_'),
    ' Van ' , ' Van_'),
    ' van ' , ' van_'),
    ' San ' , ' San_'),
    ' II' , '_II'),
    ' III' , '_III'),
    ' Lo ' , '_Lo '),
    ' O. ' , ' O._'),
    ' Da ' , ' Da_'),
    ' V. ' , ' V._'),
    ' Des ' , ' Des_'),
    ' The ' , ' The_'),
    ' the ' , ' the_'),
    ' von ' , ' von_'),
    ' del ' , ' del_'),

    'Panou' , 'Panou ^'),
    'RZA' , 'RZA ^'),
    'Taimak' , 'Taimak ^'),
    'Neha ' , 'Neha ^ '),
    'Tabu' , 'Tabu ^'),
    'Will.i.am' , 'Will.i.am ^'),
    'Pelé' , 'Pelé ^'),
    'Rihanna' , 'Rihanna ^'),
    'Aaliyah' , 'Aaliyah ^'),
    'DMX' , 'DMX ^'),
    'Cher ' , 'Cher ^ '),
    ' GQ' , ' GQ ^'),
    'Steve-O' , 'Steve-O ^'),
    'Vanity' , 'Vanity ^'),
    'Pink ' , 'Pink ^ '),
    'Ginuwine' , 'Ginuwine ^'),
    'Björk' , 'Björk ^'),
    'Madonna' , 'Madonna ^'),
    'Aliya' , 'Aliya ^'),
    'Mo\'Nique' , 'Mo\'Nique ^'),
    'Godfrey' , 'Godfrey ^'),
    'Lalaine' , 'Lalaine ^'),
    'Eminem' , 'Eminem ^'),
    'Arletty' , 'Arletty ^'),
    'Ne-Yo' , 'Ne-Yo ^'),
    'Silverman Eve' , 'Silverman Eve ^'),
    ' Common' , 'Common ^'),
    ' Bilal' , ' Bilal ^'),
    'Washington Mario' , 'Washington Mario ^'),
    'Dempsey Mario' , 'Dempsey Mario ^'),
    'Wazheir Lena' , 'Wazheir Lena ^'),
    'Ludacris' , 'Ludacris ^'),
    'Ashanti' , 'Ashanti ^'),
    ' Mako' , ' Mako ^'),
    'Orianthi' , 'Orianthi ^'),
    'Maïwenn' , 'Maïwenn ^'),
    ' Dragon ' , ' Dragon ^ '),
    ' Kajol ' , ' Kajol ^ '),
    ' Luenell ' , ' Luenell ^ '),
    'Rain Naomie' , 'Rain ^ Naomie'),
    ' Sarala ' , ' Sarala ^ '),
    'Irvin Nelly' , 'Irvin Nelly ^'),
    ' Sinbad ' , ' Sinbad ^ '),
    ' Amidou' , ' Amidou ^'),
    'Sting' , 'Sting ^'),
    'Litefoot' , 'Litefoot ^'),
    ' Ninja ' , ' Ninja ^ '),
    ' Astro ' , ' Astro ^ '),
    ' JoeyStarr ' , ' JoeyStarr ^ '),
    ' Miyavi ' , ' Miyavi ^ '),
    ' Redman ' , ' Redman ^ '),
    'Raven-Symoné' , 'Raven-Symoné ^'),
    ' Rekha ' , ' Rekha ^ '),
    ' Revathi ' , ' Revathi ^ '),
    ' E-40 ' , ' E-40 ^ '),
    'Xzibit' , 'Xzibit ^ '),
    ' Jewel ' , ' Jewel ^ '),
    'Krafft-Raschig' , 'Krafft-Raschig ^'),
    'Prabhas ' , ' Prabhas ^ '),
    'RuPaul' , 'RuPaul ^'),
    'Brahmanandam' , 'Brahmanandam ^'),
    'Silambarasan' , 'Silambarasan ^'),
    ' Santhanam' , ' Santhanam '),
    'Ice-T' , 'Ice-T ^'),
    ' Akon ' , ' Akon ^ '),
    ' Santhanam ' , ' Santhanam ^ '),

    'Steven Lee Edwards' , 'Steven Lee_Edwards'),
    'R.L._' , 'R._L.'),
    'Chris Ivan Cevic' , 'Chris_Ivan Cevic'),
    'Wilson Jermaine Heredia' , 'Wilson_Jermaine Heredia'),
    'O.L._Duke' , 'O._L. Duke'),
    'Jada Pinkett Smith' , 'Jada_Pinkett Smith'),
    'Sacha Baron Cohen' , 'Sacha_Baron Cohen'),
    'Keenen Ivory Wayans' , 'Keenen_Ivory Wayans'),
    ' David Alan Grier' , ' David_Alan Grier'),
    'Tyler James Williams' , 'Tyler_James Williams'),
    'Kristin Scott Thomas' , 'Kristin_Scott Thomas'),
    'John Carroll Lynch' , 'John_Carroll Lynch'),
    'Sheila_E.' , 'Sheila E.'),
    'Mary Kate Wiles' , 'Mary_Kate Wiles'),
    'D._L._Hughley' , 'D. L._Hughley'),
    'R. Martin Klein' , 'R. Martin_Klein'),
    'Lionel Mark Smith' , 'Lionel_Mark Smith'),
    'Philip Baker Hall' , 'Philip_Baker Hall'),
    'R. D._Call' , 'R._D. Call'),
    'R._Martin_Klein' , 'R_Martin Klein'),
    'Riley Thomas Stewart' , 'Riley Thomas_Stewart'),
    'J.R._Villarreal' , 'J._R. Villarreal'),
    'David A.R._White' , 'David A._R._White'),
    'Melissa Joan Hart' , 'Melissa Joan_Hart'),
    'Macody Lund' , 'Macody_Lund'),
    'T.R._Knight' , 'T. R._Knight'),
    'Billy Bob Thornton' , 'Billy Bob_Thornton'),
    'Marcia Gay Harden' , 'Marcia Gay_Harden'),
    'Jamie Lee Curtis' , 'Jamie Lee_Curtis'),
    'Keegan Connor Tracy' , 'Keegan Connor_Tracy'),
    'J._Smith-Cameron' , 'J. Smith-Cameron'),
    'Michelle Simone Miller' , 'Michelle_Simone Miller'),
    'Patch Mackenzie_E. ' , 'Patch Mackenzie E._'),
    'E._Danny Murphy_E. ' , 'E._Danny Murphy E. '),
    'Max von Sydow' , 'Max von_Sydow'),
    'Anna Deavere Smith' , 'Anna Deavere_Smith'),
    'Vanessa Lee Chester' , 'Vanessa Lee_Chester'),
    'Lara Jean Chorostecki' , 'Lara Jean_Chorostecki'),
    'Seann William Scott' , 'Seann William_Scott'),
    'Holly Marie Combs' , 'Holly Marie_Combs'),
    'T._R._Knight' , 'T. R._Knight'),
    'Michael Reilly Burke' , 'Michael Reilly_Burke'),
    'Xiao Shen Yang' , 'Xiao Shen_Yang'),
    'Benicio del Toro' , 'Benicio del_Toro'),
    'David Ogden Stiers' , 'David Ogden_Stiers'),
    'Helena Bonham Carter' , 'Helena Bonham_Carter'),
    'Susan May Pratt' , 'Susan May_Pratt'),
    'Nacio Herb Brown' , 'Nacio Herb_Brown'),
    'Brian Austin Green' , 'Brian Austin_Green'),
    'Raoul Max Trujillo' , 'Raoul Max_Trujillo'),

    'Stephen Barker Turner' , 'Stephen Barker_Turner'),
    'Courtney Taylor Burness' , 'Courtney Taylor_Burness'),
    'Sophie Kennedy Clark' , 'Sophie Kennedy_Clark'),
    'Sarah Jessica Parker' , 'Sarah Jessica_Parker'),
    'Jennifer Jason Leigh' , 'Jennifer Jason_Leigh'),
    'Christopher Nicholas Smith' , 'Christopher Nicholas_Smith'),
    'Joe Lo Truglio' , 'Joe Lo_Truglio'),
    ' Jonathan Rhys Meyers' , ' Jonathan Rhys_Meyers'),
    'Caleb Landry Jones' , 'Caleb Landry_Jones'),
    'Jessica Brooks Grant' , 'Jessica Brooks_Grant'),
    'Tommy Lee Jones' , 'Tommy Lee_Jones'),
    'Grace Moretz' , 'Grace_Moretz'),
    'Isild Le Besco' , 'Isild Le_Besco'),
    'Jonathan Rhys Meyers' , 'Jonathan Rhys_Meyers'),
    'Perry Laylon Ojeda' , 'Perry Laylon_Ojeda'),
    'Kirby Bliss Blanton' , 'Kirby Bliss_Blanton'),
    'Omar Benson Miller' , 'Omar Benson_Miller'),
    'Robert De Niro' , 'Robert De_Niro'),
    'Garette Ratliff Henson' , 'Garette Ratliff_Henson'),
    'W. Bush' , 'W._Bush'),
    'James Badge Dale' , 'James Badge_Dale'),
    'Penelope Ann Miller' , 'Penelope Ann_Miller'),
    'Anthony Stewart Head' , 'Anthony Stewart_Head'),
    'Jack La Rue' , 'Jack La_Rue'),
    'nthony Michael Hall' , 'Anthony Michael_Hall'),
    'Neil Patrick Harris' , 'Neil Patrick_Harris'),
    'e Le Calm' , 'e Le_Calm'),
    'David James Elliott' , 'David James_Elliott'),
    'Jackie Earle Haley' , 'Jackie Earle_Haley'),
    'Kate del Castillo' , 'Kate del_Castillo'),
    'Jennifer Schwalbach Smith' , 'Jennifer Schwalbach_Smith'),
    'Michele Lamar Richards' , 'Michele Lamar_Richards'),
    'Peter Mark Richman' , 'Peter Mark_Richman'),
    'Lee Van Cleef' , 'Lee Van_Cleef'),
    'Philip Seymour Hoffman' , 'Philip Seymour_Hoffman'),
    'Evan Rachel Wood' , 'Evan Rachel_Wood'),
    'Carice van Houten' , 'Carice van_Houten'),

    'Carlos Rodr' , 'Carlos_Rodr'),
    'Michael Dean Jacobs ' , 'Michael Dean_Jacobs '),
    'Thomas Haden Church ' , 'Thomas Haden_Church '),
    'Brian Keith Allen' , 'Brian Keith_Allen'),
    'David Tristan Birkin' , 'David Tristan_Birkin'),
    'Michael Dean Jacobs' , 'Michael Dean_Jacobs'),
    'Joe Don Baker' , 'Joe Don_Baker'),
    'Gabrielle Lopes Benites' , 'Gabrielle Lopes_Benites'),
    'Ki Hong Lee' , 'Ki Hong_Lee'),
    'Jason Scott Lee' , 'Jason Scott_Lee'),
    'William Lee Scott' , 'William Lee_Scott'),
    'Eric Christian Olsen' , 'Eric Christian_Olsen'),
    'David Hyde Pierce' , 'David Hyde_Pierce'),
    'Michael Kenneth Williams' , 'Michael Kenneth_Williams'),
    'Will Yun Lee' , 'Will Yun_Lee'),
    'Julie \'Jules\' Urich' , 'Julie \'Jules\'_Urich'),
    'Bong Soo Han' , 'Bong Soo_Han'),
    'Robert Sean Leonard' , 'Robert Sean_Leonard'),
    'Lisa Ann Walter' , 'Lisa Ann_Walter'),
    'Jose Pablo Cantillo' , 'Jose Pablo_Cantillo'),
    'Daniel Hugh Kelly' , 'Daniel Hugh_Kelly'),
    'Clifton Collins Jr' , 'Clifton Collins_Jr.'),
    'Raphael de la Sierra' , 'Raphael de_la_Sierra'),
    'Birgitte Hjort Sørensen' , 'Birgitte Hjort_Sørensen'),
    'Mohammad Nadir Khwaja' , 'Mohammad Nadir_Khwaja'),
    'David Patrick Kelly' , 'David Patrick_Kelly'),
    'Tamar van den Dop' , 'Tamar van_den_Dop'),
    'Jean-Claude Van Damme' , 'Jean-Claude Van-Damme'),
    'Fedja van Huêt' , 'Fedja van_Huêt'),
    'Raúl Juliá' , 'Raúl Juliá'),
    'Julanne Chidi Hill' , 'Julanne Chidi_Hill'),
    'Sarah Wayne Callies' , 'Sarah WayneCallies'),
    'Lou Diamond Phillips' , 'Lou Diamond_Phillips'),
    'Joanna \' JoJo \' Levesque' , 'Joanna \'JoJo\'_Levesque'),
    'Julio Oscar Mechoso' , 'Julio Oscar_Mechoso'),
    'Michael Clarke Duncan' , 'Michael Clarke_Duncan'),
    'Jean Michel Paré' , 'Jean Michel Paré'),
    'Mary Kay Place' , 'Mary Kay_Place'),
    'Joseph Julian Soria' , 'Joseph Julian_Soria'),
    'Harry Dean Stanton' , 'Harry Dean_Stanton'),
    'Andrew Dice Clay' , 'Andrew Dice_Clay'),
    ' Danielle von Zerneck' , ' Danielle von_Zerneck'),
    'Debra Jo Rupp' , 'Debra Jo_Rupp'),

    'Juan José Campanella' , 'Juan José_Campanella'),
    'Juan Eduardo Palacios' , 'Juan Eduardo_Palacios'),
    'Tim Blake Nelson' , 'Tim Blake_Nelson'),
    'Mary Elizabeth Winstead' , 'Mary Elizabeth_Winstead'),
    'Mary Tyler Moore' , 'Mary Tyler_Moore'),
    'Edward James Olmos' , 'Edward James_Olmos'),
    'Daphnée Duplaix Samuel' , 'Daphnée Duplaix_Samuel'),
    'LL Cool J' , 'LL Cool_J'),
    'Thomas Ian Griffith' , 'Thomas Ian_Griffith'),
    'Makenzie Vega Norfolk' , 'Makenzie Vega_Norfolk'),
    'David Jason Perez' , 'David Jason_Perez'),
    'Charles Martin Smith' , 'Charles Martin_Smith'),
    'Maï Anh Le' , 'Maï Anh_Le'),
    'Jaran \'See Tao\' Petcharoen' , 'Jaran \'See Tao\'_Petcharoen'),
    'Stéphanie Lagarde' , 'Stéphanie Lagarde'),
    'Vincent Byrd Le_Sage' , 'Vincent Byrd_Le_Sage'),
    'Ronnie Gene Blevins' , 'Ronnie Gene_Blevins'),
    ' James Earl Jones' , 'James Earl_Jones'),
    'Bryce Dallas Howard' , 'Bryce Dallas_Howard'),
    'De_Anna Joy Brooks' , 'De_Anna Joy_Brooks'),
    'F.A._Turner' , 'F. A._Turner'),
    'Angelo Barra Moreira' , 'Angelo Barra_Moreira'),
    'Chao Li Chi' , 'Chao Li_Chi'),
    'Tony Leung Chiu-Wai' , 'Tony Leung_Chiu-Wai'),
    'Rae Dawn Chong' , 'Rae Dawn_Chong'),
    'Tom Everett Scott' , 'Tom Everett_Scott'),
    'Robert John Burke' , 'Robert John_Burke'),
    'Michael Bailey Smith' , 'Michael Bailey_Smith'),
    'Jessica Brown Findlay' , 'Jessica Brown_Findlay'),
    'Joey Lauren Adams' , 'Joey Lauren_Adams'),
    'Jeremy James Kissner' , 'Jeremy James_Kissner'),
    'Natasha Gregson Wagner' , 'Natasha Gregson_Wagner'),
    'Mark Boone Junior' , 'Mark Boone_Junior'),
    'Nolan Gerard Funk' , 'Nolan Gerard_Funk'),
    'Van_Johnson' , 'Van Johnson'),
    'James Van_Der Beek' , 'James Van_Der_Beek'),
    'Merrie Lynn Ross' , 'Merrie Lynn_Ross'),
    'Philip Chan Yan-Kin' , 'Philip Chan_Yan-Kin'),
    'Sara Malakul Lane' , 'Sara Malakul_Lane'),
    'Rachael Leigh Cook' , 'Rachael Leigh_Cook'),
    'Michael Jai White' , 'Michael Jai_White'),
    'Chad Michael Murray' , 'Chad Michael_Murray'),
    'Michelle Van_Der Water' , 'Michelle Van_Der_Water'),
    'Tamar van_den Dop' , 'Tamar van_den_Dop'),
    'Jamie Campbell Bower' , 'Jamie Campbell_Bower'),
    'Frederique van_der Wal' , 'Frederique van_der_Wal'),
    'Randall Duk Kim' , 'Randall Duk_Kim'),
    'Billy Ray Cyrus' , 'Billy Ray_Cyrus'),
    'George Buck Flower' , 'George Buck_Flower'),
    'Callum Keith Rennie' , 'Callum Keith_Rennie'),
    'Damian Jewan Lee' , 'Damian Jewan_Lee'),
    'David Roland Frank' , 'David Roland_Frank'),
    'Ella Rae Peck' , 'Ella Rae_Peck'),
    'Christopher Evan Welch' , 'Christopher Evan_Welch'),
    'Mary Elizabeth Mastrantonio' , 'Mary Elizabeth_Mastrantonio'),
    'Elizabeth of Toro' , 'Elizabeth of_Toro'),
    'Shah Rukh Khan' , 'Shah Rukh_Khan'),
    'Lisa Gay Hamilton' , 'Lisa Gay_Hamilton'),
    'Sarah Jessica Parker' , 'Sarah Jessica_Parker'),
    'Maggie Elizabeth Jones' , 'Maggie Elizabeth_Jones'),
    'Haley Joel Osmen' , 'Haley Joel_Osment'),
    'Anna Maria Horsford' , 'Anna Maria_Horsford'),
    'Joel David Moore' , 'Joel David_Moore'),
    'Holly Robinson Peete' , 'Holly Robinson_Peete'),
    'Julie Ann Emery' , 'Julie Ann_Emery'),
    'Lynn \'Red\' Williams' , 'Lynn \'Red\'_Williams'),
    'Thomas Haden Church' , 'Thomas Haden_Church'),
    'John Phillip Law' , 'John Phillip_Law'),
    'Hadley Belle Miller' , 'Hadley Belle_Miller'),
    'Audrey Lynn Tennent' , 'Audrey Lynn_Tennent'),
    'Rickey D\'Shon Collins' , 'Rickey D\'Shon_Collins'),
    'Edward Everett Horton' , 'Edward Everett_Horton'),
    'Sarah Michelle Gellar' , 'Sarah Michelle_Gellar '),
    'Jon Bon Jovi' , 'Jon Bon_Jovi'),
    'Amber Rose Revah' , 'Amber Rose_Revah'),
    'Klaus Maria Brandauer' , 'Klaus Maria_Brandauer'),
    'M.L. Piyapas Bhirombhakdi' , 'M.L. Piyapas_Bhirombhakdi'),
    'Godfrey ^ Cambridge' , 'Godfrey Cambridge'),
    'Christopher Corey Smith' , 'Christopher Corey_Smith'),
    'Dee Dee Greene' , 'Dee Dee_Greene'),
    'Billy Dee Williams' , 'Billy Dee_Williams'),
    'Dee Bradley Bak' , 'Dee Bradley_Bak'),
    'Sophia Taylor Ali' , 'Sophia Taylor_Ali'),
    'Thomas Ian Nicholas' , 'Thomas Ian_Nicholas'),
    'Meredith Scott Lynn' , 'Meredith Scott_Lynn'),
    'Jeppe Beck Laursen' , 'Jeppe Beck_Laursen'),
    'Evy Kasseth Røsten' , 'Evy Kasseth_Røsten'),
    'Stig Frode Henriksen' , 'Stig Frode_Henriksen'),
    'Eddie Kaye Thomas' , 'Eddie Kaye_Thomas'),
    'Alexandra Maria Lara' , 'Alexandra Maria_Lara'),
    'Sheri Moon Zombie' , 'Sheri Moon_Zombie'),
    'Juan Carlos Montoya' , 'Juan Carlos_Montoya'),
    'Allan Bryan Weku' , 'Allan Bryan_Weku'),
    'Luis Fernando Peña' , 'Luis Fernando_Peña'),
    'Harold House Moore' , 'Harold House_Moore'),
    'Catalina Sandino Moreno' , 'Catalina Sandino_Moreno'),
    'Ana Claudia Talancón' , 'Ana Claudia_Talancón'),
    'John Canada Terrell' , 'John Canada_Terrell'),
    'Christie Lynn Smith' , 'Christie Lynn_Smith'),
    'Anthony \'Citric\' Campos' , 'Anthony \'Citric\'_Campos'),
    'Soha Ali Khan' , 'Soha Ali_Khan'),
    'Jonathan Taylor Thomas' , 'Jonathan Taylor_Thomas'),
    'Lily Autumn Page' , 'Lily Autumn_Page'),
    'Lara Jill Miller' , 'Lara Jill_Miller'),
    'Lara Flynn Boyle' , 'Lara Flynn_Boyle'),
    'Jennifer Love Hewitt' , 'Jennifer Love_Hewitt'),
    'Josep Maria Pou' , 'Josep Maria_Pou'),
    'James Anthony Pearson' , 'James Anthony_Pearson'),
    'Jonny Lee Miller' , 'Jonny Lee_Miller'),
    'Sisq' , 'Sisqó ^'),
    'Morgan Peter Brown ' , 'Morgan Peter_Brown '),
    'James Francis Kelly_III' , 'James Francis_Kelly_III'),
    'María Conchita Alonso' , 'María Conchita_Alonso'),
    'Lisa Hart Carroll' , 'Lisa Hart_Carroll'),
    'Per Christian Ellefsen' , 'Per Christian_Ellefsen'),
    'Marit Pia Jacobsen' , 'Marit Pia_Jacobsen'),
    'Erik Per Sullivan' , 'Erik Per_Sullivan'),
    'Juan Maria Almonte' , 'Juan Maria_Almonte'),
    'Nicole Ari Parker' , 'Nicole Ari_Parker'),
    'Gary \'G. Thang\' Johnson' , 'Gary \'G._Thang\'_Johnson'),
    '  ' , ' '),

    'Christa Brittany Allen', 'Christa Brittany_Allen'),
    'Jamyang Jamtsho Wangchuk' , 'Jamyang Jamtsho_Wangchuk'),
    'Ahmad Khan Mahmoodzada' , 'Ahmad Khan_Mahmoodzada'),
    'Patricia Reyes Spíndola' , 'Patricia Reyes_Spíndola'),
    'June Carter Cash' , 'June Carter_Cash'),
    'Harley Jane Kozak' , 'Harley Jane_Kozak'),
    'Jodi Lyn O\'Keefe' , 'Jodi Lyn_O\'Keefe'),
    'Lisa Roberts Gillan' , 'Lisa Roberts_Gillan'),
    'Eva Amurri Martino' , 'Eva Amurri_Martino'),
    'Jeffrey Dean Morgan' , 'Jeffrey Dean_Morgan'),
    'Bergüzar Korel' , 'Bergüzar Korel'),
    'Muhammed Necati Şaşmaz' , 'Muhammed Necati_Şaşmaz'),
    'Gordon Lam Ka-Tung' , 'Gordon Lam_Ka-Tung'),
    'Gael García Bernal' , 'Gael García_Bernal'),
    'Stephen Tyrone Williams' , 'Stephen Tyrone_Williams'),
    'Christopher Jordan Wallace' , 'Christopher_Jordan Wallace'),
    'Eddie Cheung Siu-Fai' , 'Eddie Cheung_Siu-Fai'),
    'Michael Robert Brandon' , 'Michael Robert_Brandon'),
    'Lesley Ann Warren' , 'Lesley Ann_Warren'),
    'Natalie Stephany Aguilar' , 'Natalie Stephany_Aguilar'),
    'Louise Lemoine Torrès' , 'Louise Lemoine_Torrès'),
    'Emilio Tuki Hito' , 'Emilio Tuki_Hito'),
    'Benjamin Jay Davis' , 'Benjamin Jay_Davis'),
    'Abu George Shibli ' , 'Abu George_Shibli '),
    'Sheryl Lee Ralph' , 'Sheryl Lee_Ralph'),
    'Gordon Liu Chia-Hui' , 'Gordon Liu_Chia-Hui'),
    'Abu George Shibli' , 'Abu George_Shibli'),
    'Sarah Jane Morris' , 'Sarah Jane_Morris'),
    'Wen Bin Huang' , 'Wen Bin_Huang'),
    'John Michael Higgins' , 'John Michael_Higgins'),
    'Wendy Raquel Robinson' , 'Wendy Raquel_Robinson'),
    'Monique Gabriela Curnen' , 'Monique Gabriela_Curnen'),
    'Adrián Alonso Barona' , 'Adrián Alonso_Barona'),
    'William Morgan Sheppard' , 'William Morgan_Sheppard'),
    'Weird Al' , 'Weird_Al'),
    'Putu Dinda Pratika' , 'Putu Dinda_Pratika'),
    'Puti Sri Candra Dewi' , 'Puti Sri_Candra_Dewi'),
    'Ni Made Megahadi Pratiwi' , 'Ni Made_Megahadi_Pratiwi'),
    'Robin Atkin Downes' , 'Robin Atkin_Downes'),
    'Rima Te Wiata' , 'Rima Te_Wiata'),
    'Tony Leung Ka-Fai' , 'Tony Leung_Ka-Fai'),
    'Marcus Carl Franklin' , 'Marcus Carl_Franklin'),
    'Roger Guenveur Smith' , 'Roger Guenveur_Smith'),
    'Deborah Kara Unger' , 'Deborah Kara_Unger'),
    'James Arnold Taylor' , 'James Arnold_Taylor'),
    'Jacqueline MacInnes Wood' , 'Jacqueline MacInnes_Wood'),
    'Wotan Wilke Möhring' , 'Wotan Wilke_Möhring'),
    'Larry the_Cable Guy' , 'Larry the_Cable_Guy'),
    'Sean Patrick Thomas' , 'Sean Patrick_Thomas'),
    'Patrick_Thomas Eve' , 'Patrick_Thomas Eve ^'),
    'Jayvee Mai The_Hiep' , 'Jayvee Mai_The_Hiep'),
    'Eva Marie Saint' , 'Eva Marie_Saint'),
    'Anthony Tony Shalhoub' , 'Anthony Tony_Shalhoub'),
    'Sean Michael Afable' , 'Sean Michael_Afable'),
    'Ana Maria Guran' , 'Ana Maria_Guran'),
    'Kitty Zhang Yuqi' , 'Kitty Zhang_Yuqi'),
    'Fred Dalton Thompson' , 'Fred Dalton_Thompson'),
    'Jill Marie Jones' , 'Jill Marie_Jones'),
    'Karin Anna Cheung' , 'Karin Anna_Cheung'),
    'Anna Claire Sneed' , 'Anna Claire_Sneed'),
    'Jonathan Ke Quan' , 'Jonathan Ke_Quan'),
    'Mary Kay Bergman' , 'Mary Kay_Bergman'),

    'Mary Lynn Rajskub' , 'Mary Lynn_Rajskub'),
    ' Ellen Hamilton Latzen' , ' Ellen Hamilton_Latzen'),
    'Ana López Mercado' , 'Ana López_Mercado'),
    'Jonathan Erickson Eisley' , 'Jonathan Erickson_Eisley'),
    'Anika Noni Rose' , 'Anika Noni_Rose'),
    'Amber Marie Bollinger' , 'Amber Marie_Bollinger'),
    'Tung Thanh Tran' , 'Tung Thanh_Tran'),
    'James Patrick Stuart' , 'James Patrick_Stuart'),
    'Lou Taylor Pucci' , 'Lou Taylor_Pucci'),
    'Jamie Renée Smith' , 'Jamie Renée_Smith'),
    'Jean François Heckel' , 'Jean François_Heckel'),
    'Tupac Amaru Shakur' , 'Tupac Amaru_Shakur'),
    'Yasmine Al Massri' , 'Yasmine Al_Massri'),
    'Jeff Daniel Phillips' , 'Jeff Daniel_Phillips'),
    'Malcolm David Kelley' , 'Malcolm David_Kelley'),
    'Leon Isaac Kennedy' , 'Leon Isaac_Kennedy'),
    'Sean Patrick Flanery' , 'Sean Patrick_Flanery'),
    'R._D._Call' , 'R. D._Call'),
    'David Della Rocco' , 'David Della_Rocco'),
    'Elina Abai Kyzy' , 'Elina Abai_Kyzy'),
    'Aishwarya Rai Bachchan' , 'Aishwarya Rai_Bachchan'),
    'Mads Sjøgård Pettersen' , 'Mads Sjøgård_Pettersen'),
    'Robert Daniel Sloan' , 'Robert Daniel_Sloan'),
    'David Lee Smith' , 'David Lee_Smith'),
    'Vanessa Bell Calloway' , 'Vanessa Bell_Calloway'),
    'Gralen Bryant Banks' , 'Gralen Bryant_Banks'),
    'David Sanin Paz' , 'David Sanin_Paz'),
    'Brad William Henke' , 'Brad William_Henke'),
    ' Lail Molly Hagan' , '_Lail Molly Hagan'),
    'Ten Years After' , 'Ten Years_After'),
    'Roy Richard Grinker' , 'Roy Richard_Grinker'),
    'D. David Morin' , 'D. David_Morin'),
    'Sumeet Darshan Dobhal' , 'Sumeet Darshan_Dobhal'),
    'Fadi Abi Samra' , 'Fadi Abi_Samra'),
    'Matthew Gray Gubler' , 'Matthew Gray_Gubler'),
    'Ernesto Gómez Cruz' , 'Ernesto Gómez_Cruz'),
    'Cyndi Mayo Davis' , 'Cyndi Mayo_Davis'),
    'Ian Michael Smith ' , 'Ian Michael_Smith '),
    'Charles Henry Wyson' , 'Charles Henry_Wyson'),
    'Jesse Lee Soffer' , 'Jesse Lee_Soffer'),
    'Stephen Campbell Moore ' , 'Stephen Campbell_Moore '),
    'Spencer Treat Clark' , 'Spencer Treat_Clark'),
    'Kassovitz Rufus' , 'Kassovitz Rufus ^'),
    'John Patrick Amedori' , 'John Patrick_Amedori'),
    'Robert Ellis Orrall' , 'Robert Ellis_Orrall'),
    'Skye McCole Bartusiak' , 'Skye McCole_Bartusiak'),
    'Kate Lynn Evans ' , 'Kate Lynn_Evans '),
    ' Milewski ' , '_Milewski '),
    'Sean Cameron Michael' , 'Sean Cameron_Michael'),
    'Jane Galloway Heitz' , 'Jane Galloway_Heitz'),
    'Kate Lynn Evans' , 'Kate Lynn_Evans'),
    'Thomas Francis Walsh_III' , 'Thomas Francis_Walsh_III'),
    'Olivia Taylor Dudley' , 'Olivia Taylor_Dudley'),
    'Ingrid Bolsø Berdal' , 'Ingrid Bolsø_Berdal'),
    'Kevin Peter Hall' , 'Kevin Peter_Hall'),
    'Ginés García Millán' , 'Ginés García_Millán'),
    ' María Mercedes Villagra ' , ' María Mercedes_Villagra '),
    'Amanda Redman ^' , 'Amanda Redma'),
    'Nouva Monika Wahlgren' , 'Nouva Monika_Wahlgren'),
    'Jamil Walker Smith' , 'Jamil Walker_Smith'),
    'Jean Michel Paré' , 'Jean Michel_Paré'),
    'Jon Ted Wynne' , 'Jon Ted_Wynne'),
    'Christoph Maria Herbst' , 'Christoph_Maria Herbst'),
    'Mary Beth Hurt' , 'Mary Beth_Hurt'),
    'Rae\'Ven Larrymore_Kelly' , 'Rae\'Ven Larrymore_Kelly'),
    'Taylor Scott Olson' , 'Taylor Scott_Olson'),
    'Henry Ian Cusick ' , 'Henry Ian_Cusick '),
    'Maryiam Palvin Almani' , 'Maryiam Palvin_Almani'),
    'L. Scott Caldwel' , 'L. Scott_Caldwel'),
    'Roscoe Lee Browne' , 'Roscoe Lee_Browne'),
    'Rae\'Ven Larrymore Kelly' , 'Rae\'Ven Larrymore_Kelly'),
    'Dakota Blue Richards' , 'Dakota Blue_Richards'),
    'Jerome Elston Scott' , 'Jerome Elston_Scott'),
    'Reza Sixo Safai' , 'Reza Sixo_Safai'),
    'Eric Allan Kramer' , 'Eric Allan_Kramer'),
    'John Cameron Mitchell' , 'John Cameron_Mitchell'),
    'Anthony Ray Parker' , 'Anthony Ray_Parker'),
    'Wen Yann Shih' , 'Wen Yann_Shih'),
    'Tran Nu Yên-Khê' , 'Tran Nu_Yên-Khê'),
    'Gregory Russell Cook' , 'Gregory Russell_Cook'),
    'Lauren Lee Smith' , 'Lauren Lee_Smith'),
    ' Michael Aaron Milligan' , ' Michael Aaron_Milligan'),
    'Sydney Tamiia Poitier' , 'Sydney Tamiia_Poitier'),
    'Emma Eliza Regan' , 'Emma Eliza_Regan'),
    'Aja Naomi King' , 'Aja Naomi_King'),
    'Connor Christopher Levins' , 'Connor Christopher_Levins'),
    'Sandra Ellis Lafferty' , 'Sandra Ellis_Lafferty'),
    'Thomas Bo Larsen' , 'Thomas Bo_Larsen'),
    'Gian Maria Volonté' , 'Gian Maria_Volonté'),
    'Ólafur Darri Ólafsson' , 'Ólafur Darri_Ólafsson'),
    'June Diane Raphael' , 'June Diane_Raphael'),
    'Catherine Lloyd Burns' , 'Catherine Lloyd_Burns'),
    'Alyn Lind' , 'Alyn_Lind'),
    'Travis Aaron Wade' , 'Travis Aaron_Wade'),
    'Moses Jacob Storm ' , 'Moses Jacob_Storm '),
    'Ricky Dean Logan' , 'Ricky Dean_Logan'),
    'Anne Louise Hassing ' , 'Anne Louise_Hassing '),
    'Ty Thomas Reed' , 'Ty Thomas_Reed'),
    ' Hui Lou Chen' , ' Hui Lou_Chen'),
    'Harley Quinn Smith' , 'Harley Quinn_Smith'),
    'Paula Jai Parker' , 'Paula Jai_Parker'),
    'Hui Lou Chen' , 'Hui Lou_Chen'),
    'Keshia Knight Pulliam' , 'Keshia Knight_Pulliam'),
    'Hatha Yogi Baba' , 'Hatha Yogi_Baba'),
    'Pant Shirt Baba' , 'Pant Shirt_Baba'),
    'Shriman Umeshanad Brahmachari' , 'Shriman Umeshanad_Brahmachari'),
    'Patrick Tse Yin' , 'Patrick Tse_Yin'),
    'Adam David Thompson' , 'Adam David_Thompson'),
    'Vicellous Reon Shannon' , 'Vicellous Reon_Shannon'),
    'Machine Gun Kelly ' , 'Machine Gun_Kelly '),
    'David W. Ross' , 'David W._Ross'),
    'John Ross Bowie' , 'John Ross_Bowie'),
    'John Benjamin Hickey' , 'John Benjamin_Hickey'),
    'Tara Alice Scully' , 'Tara Alice_Scully'),
    'Dick Anthony Williams' , 'Dick Anthony_Williams'),
    'James Robertson Justice' , 'James Robertson_Justice'),
    'Sophie Charlotte Conrad' , 'Sophie Charlotte_Conrad'),
    'Juan Carlos Hernández' , 'Juan Carlos_Hernández'),
    'Juan Carlos Copes' , 'Juan Carlos_Copes'),
    'Lisa Nicole Carson' , 'Lisa Nicole_Carson'),
    'Charles Malik Whitfield' , 'Charles Malik_Whitfield'),
    'Paco Christian Prieto' , 'Paco Christian_Prieto'),
    'Rocky Mayor Anderson' , 'Rocky Mayor_Anderson'),
    'Jonathan Daniel Brown' , 'Jonathan Daniel_Brown'),
    'Mia Drake Inderbitzin' , 'Mia Drake_Inderbitzin'),
    'John Bennett Perry' , 'John Bennett_Perry'),
    'Wilbur \'Hi-Fi\' White' , 'Wilbur \'Hi-Fi\'_White'),
    'Lenny Von Dohlen' , 'Lenny Von_Dohlen'),
    'Christopher Robin Miller' , 'Christopher Robin_Miller'),
    'Chase Wright Vanek' , 'Chase Wright_Vanek'),
    'Miguel Ángel Solá' , 'Miguel Ángel_Solá'),
    'José Luis García Pérez' , 'José_Luis García_Pérez')
FROM movie_dataset;


SELECT columnReplaced, LENGTH(columnReplaced) - LENGTH(REPLACE(columnReplaced, ' ', ''))
FROM temporalCast WHERE LENGTH(columnReplaced) - LENGTH(REPLACE(columnReplaced, ' ', ''))  % 2 = 0;



DROP TABLE IF EXISTS cast;
CREATE TABLE cast (
    name VARCHAR(250) PRIMARY KEY
);


SELECT
    columnReplaced,
    SUBSTRING_INDEX(columnReplaced, ' ', 15),
      SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 8), ' ', -12), ' ', 2),
      SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 8), ' ', -6), ' ', 2),
      SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 8), ' ', -4), ' ', 2),
      SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 8), ' ', -2), ' ', 2),
      SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 10), ' ', -2)

FROM temporalCast
WHERE columnReplaced LIKE '%Jr.';

DROP TABLE IF EXISTS resultados;
CREATE TABLE resultados (columna VARCHAR(255));



INSERT INTO resultados(columna)
SELECT
    REPLACE(
        REPLACE(
            SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 8), ' ', -12), ' ', 2),
                '_' ,' '),
                '^ ', '')
FROM temporalCast;

INSERT INTO resultados(columna)
SELECT
    REPLACE(
        REPLACE(
    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 8), ' ', -6), ' ', 2),
        '_' ,' '),
        '^ ', '')
FROM temporalCast;

INSERT INTO resultados(columna)
SELECT
    REPLACE(
        REPLACE(
    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 8), ' ', -4), ' ', 2),
        '_' ,' '),
        '^ ', '')
FROM temporalCast;

INSERT INTO resultados(columna)
SELECT

    REPLACE(
        REPLACE(
    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 8), ' ', -2), ' ', 2),
        '_' ,' '),
        '^ ', '')
FROM temporalCast;

INSERT INTO resultados(columna)
SELECT
    REPLACE(
        REPLACE(
    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(columnReplaced, ' ', 10), ' ', 10), ' ', -2),
        '_' ,' '),
        '^ ', '')
FROM temporalCast;


DROP TABLE IF EXISTS cast;
CREATE TABLE cast (
    name VARCHAR(250) PRIMARY KEY
);

INSERT into cast
(SELECT DISTINCT columna
 FROM resultados
 WHERE columna IS NOT NULL)







